# Generated by Django 5.2.7 on 2026-02-23 15:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


def create_singletons(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    WaxingSettings = apps.get_model("waxing", "WaxingSettings")
    WaxingContent = apps.get_model("waxing", "WaxingContent")

    WaxingSettings.objects.using(db_alias).get_or_create(singleton_key=1)
    WaxingContent.objects.using(db_alias).get_or_create(
        singleton_key=1,
        defaults={
            "title": "",
            "short_description": "",
            "description": "",
            "recommendations_intro_text": "",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreaCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="waxing/area_categories/"
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("show_packs", models.BooleanField(default=True)),
                (
                    "area_sort",
                    models.CharField(
                        choices=[
                            ("price_asc", "Price asc"),
                            ("price_desc", "Price desc"),
                            ("az", "A-Z"),
                            ("za", "Z-A"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "pack_sort",
                    models.CharField(
                        choices=[
                            ("price_asc", "Price asc"),
                            ("price_desc", "Price desc"),
                            ("az", "A-Z"),
                            ("za", "Z-A"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "pack_position",
                    models.CharField(
                        choices=[("first", "First"), ("last", "Last")],
                        default="first",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Pack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("price", models.PositiveIntegerField()),
                (
                    "promotional_price",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="waxing/packs/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="waxing/sections/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "featured_sort",
                    models.CharField(
                        choices=[
                            ("price_asc", "Price asc"),
                            ("price_desc", "Price desc"),
                            ("az", "A-Z"),
                            ("za", "Z-A"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="WaxingContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("recommendations_intro_text", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="waxing/content/"
                    ),
                ),
                (
                    "benefits_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="waxing/content/"
                    ),
                ),
                (
                    "recommendations_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="waxing/content/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Waxing content",
                "verbose_name_plural": "Waxing content",
            },
        ),
        migrations.CreateModel(
            name="WaxingSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("public_visible", models.BooleanField(default=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("allow_booking", models.BooleanField(default=True)),
                ("show_prices", models.BooleanField(default=True)),
                ("featured_enabled", models.BooleanField(default=True)),
                (
                    "default_area_sort",
                    models.CharField(
                        choices=[
                            ("price_asc", "Price asc"),
                            ("price_desc", "Price desc"),
                            ("az", "A-Z"),
                            ("za", "Z-A"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "default_pack_sort",
                    models.CharField(
                        choices=[
                            ("price_asc", "Price asc"),
                            ("price_desc", "Price desc"),
                            ("az", "A-Z"),
                            ("za", "Z-A"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "default_pack_position",
                    models.CharField(
                        choices=[("first", "First"), ("last", "Last")],
                        default="first",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Waxing settings",
                "verbose_name_plural": "Waxing settings",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("price", models.PositiveIntegerField()),
                (
                    "promotional_price",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("short_description", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="waxing/areas/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="waxing.areacategory",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="waxing.section",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="PackArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_packs",
                        to="waxing.area",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_areas",
                        to="waxing.pack",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="pack",
            name="areas",
            field=models.ManyToManyField(
                related_name="packs", through="waxing.PackArea", to="waxing.area"
            ),
        ),
        migrations.AddField(
            model_name="pack",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packs",
                to="waxing.section",
            ),
        ),
        migrations.CreateModel(
            name="FeaturedItemOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_kind",
                    models.CharField(
                        choices=[("area", "Area"), ("pack", "Pack")], max_length=10
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_orders",
                        to="waxing.section",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="areacategory",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="waxing.section",
            ),
        ),
        migrations.CreateModel(
            name="RecommendationItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="waxing.waxingcontent",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="waxing.waxingcontent",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BenefitItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("detail", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="waxing.waxingcontent",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="packarea",
            index=models.Index(
                fields=["pack", "order"], name="waxing_pack_pack_id_842467_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="packarea",
            constraint=models.UniqueConstraint(
                fields=("pack", "area"), name="uq_waxing_pack_area_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="pack",
            index=models.Index(
                fields=["section", "order"], name="waxing_pack_section_dab616_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pack",
            index=models.Index(
                fields=["section", "is_featured"], name="waxing_pack_section_adec10_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("section"),
                name="uq_waxing_pack_name_ci_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotional_price__isnull", True),
                    ("promotional_price__lt", models.F("price")),
                    _connector="OR",
                ),
                name="ck_waxing_pack_promo_lt_price",
            ),
        ),
        migrations.AddIndex(
            model_name="featureditemorder",
            index=models.Index(
                fields=["section", "order"], name="waxing_feat_section_a144ca_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="featureditemorder",
            constraint=models.UniqueConstraint(
                fields=("section", "item_kind", "item_id"),
                name="uq_waxing_featured_item_unique_per_section",
            ),
        ),
        migrations.AddIndex(
            model_name="areacategory",
            index=models.Index(
                fields=["section", "order"], name="waxing_area_section_777a5c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="areacategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("section"),
                name="uq_waxing_area_category_name_ci_per_section",
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["section", "category", "order"],
                name="waxing_area_section_f8e248_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["section", "is_featured"], name="waxing_area_section_d7c4ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("section"),
                name="uq_waxing_area_name_ci_per_section",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotional_price__isnull", True),
                    ("promotional_price__lt", models.F("price")),
                    _connector="OR",
                ),
                name="ck_waxing_area_promo_lt_price",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationitem",
            index=models.Index(
                fields=["content", "order"], name="waxing_reco_content_dcc4a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faqitem",
            index=models.Index(
                fields=["content", "order"], name="waxing_faqi_content_94ef0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefititem",
            index=models.Index(
                fields=["content", "order"], name="waxing_bene_content_c61ec1_idx"
            ),
        ),
        migrations.RunPython(create_singletons, migrations.RunPython.noop),
    ]
