# Generated by Django 5.2.7 on 2026-02-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waxing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pack",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration__isnull", True), ("duration__gt", 0), _connector="OR"
                ),
                name="ck_waxing_area_duration_gt_0_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="pack",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration__isnull", True), ("duration__gt", 0), _connector="OR"
                ),
                name="ck_waxing_pack_duration_gt_0_or_null",
            ),
        ),
    ]
