# Generated by Django 5.2.7 on 2026-01-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authcodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otplogincode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("dni_change", "DNI change"),
                    ("dni_claim", "DNI claim"),
                ],
                db_index=True,
                default="login",
                max_length=20,
            ),
        ),
    ]
