# Generated by Django 5.2.7 on 2026-01-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_full_name_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="avatar_url",
            new_name="google_avatar_url",
        ),
        migrations.AddField(
            model_name="client",
            name="custom_avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="clients/avatars/"
            ),
        ),
    ]
