# Generated by Django 5.2.7 on 2026-01-07 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0012_category_default_sort_category_include_journeys_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("batch_id", models.UUIDField(db_index=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_days",
                        to="catalog.journey",
                    ),
                ),
            ],
            options={
                "db_table": "availability_days",
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "availability_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="scheduling.availabilityday",
                    ),
                ),
            ],
            options={
                "db_table": "availability_slots",
            },
        ),
        migrations.CreateModel(
            name="ScheduleBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_blocks",
                        to="catalog.journey",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_blocks",
            },
        ),
        migrations.AddIndex(
            model_name="availabilityday",
            index=models.Index(
                fields=["journey", "date"], name="availabilit_journey_4d4757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityday",
            index=models.Index(fields=["date"], name="availabilit_date_561ea9_idx"),
        ),
        migrations.AddIndex(
            model_name="availabilityslot",
            index=models.Index(
                fields=["availability_day"], name="availabilit_availab_ab4be9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityslot",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="ck_availability_slot_start_lt_end",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleblock",
            index=models.Index(
                fields=["journey", "date"], name="schedule_bl_journey_b1efa7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleblock",
            index=models.Index(fields=["date"], name="schedule_bl_date_02e93b_idx"),
        ),
        migrations.AddConstraint(
            model_name="scheduleblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_time__lt", models.F("end_time"))),
                name="ck_schedule_block_start_lt_end",
            ),
        ),
    ]
