# Generated by Django 5.2.7 on 2025-11-06 14:43

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zone",
            name="slug",
        ),
        migrations.AddField(
            model_name="zone",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["category", "name"], name="catalog_zon_categor_826aa2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("category"),
                name="uq_zone_name_ci_per_category",
            ),
        ),
    ]
