# Generated by Django 5.2.7 on 2025-11-10 13:00

import datetime
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_zone_slug_zone_category_alter_zone_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subzone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="combo",
            old_name="current_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="combo",
            old_name="previous_price",
            new_name="promotional_price",
        ),
        migrations.RenameField(
            model_name="combostepitem",
            old_name="duration_min",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="treatmentzoneconfig",
            old_name="duration_min",
            new_name="duration",
        ),
        migrations.RenameField(
            model_name="treatmentzoneconfig",
            old_name="previous_price",
            new_name="promotional_price",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="durations",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="intensities",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="objectives",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="treatment_types",
        ),
        migrations.RemoveField(
            model_name="combostep",
            name="parallel",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="previous_price",
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 7, 744284, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="combo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 12, 501964, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="combo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="combo",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="combo",
            name="modal_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="combo",
            name="modal_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combo",
            name="modal_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="combo",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="combo",
            name="rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="combo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="comboingredient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 20, 931430, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comboingredient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="combostep",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 24, 224222, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="combostep",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="combostepitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 26, 850855, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="combostepitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="durationbucket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 30, 136163, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="durationbucket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="intensitylevel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 35, 236632, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="intensitylevel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 38, 997569, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journey",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="objective",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 41, 662233, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objective",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 44, 184567, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="treatment",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="treatment",
            name="requires_zones",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="treatmenttype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 47, 182535, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatmenttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="treatmentzoneconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 49, 944310, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="treatmentzoneconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="zone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 12, 59, 52, 511772, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zone",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="combo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="catalog.journey",
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="comboingredient",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.treatment"
            ),
        ),
        migrations.AlterField(
            model_name="comboingredient",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.zone",
            ),
        ),
        migrations.AlterField(
            model_name="combostepitem",
            name="order_hint",
            field=models.CharField(
                choices=[
                    ("AL_PRINCIPIO", "Al principio"),
                    ("AL_MEDIO", "Indistinto"),
                    ("AL_FINAL", "Al final"),
                ],
                default="AL_MEDIO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="combostepitem",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.treatment"
            ),
        ),
        migrations.AlterField(
            model_name="combostepitem",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.zone",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="catalog.journey",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="treatmentzoneconfig",
            name="body_position",
            field=models.CharField(
                blank=True,
                choices=[("boca-arriba", "Boca arriba"), ("boca-abajo", "Boca abajo")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treatmentzoneconfig",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.zone"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="zones",
                to="catalog.category",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="catalog_cat_slug_695af4_idx"),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(
                fields=["category", "title"], name="catalog_tre_categor_1dbe44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatment",
            index=models.Index(fields=["slug"], name="catalog_tre_slug_90cb65_idx"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("slug"),
                name="uq_category_slug_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="ck_combo_price_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotional_price__isnull", True),
                    ("promotional_price__gt", 0),
                    _connector="OR",
                ),
                name="ck_combo_promo_gt_0_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotional_price__isnull", True),
                    ("promotional_price__lt", models.F("price")),
                    _connector="OR",
                ),
                name="ck_combo_promo_lt_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="combostep",
            constraint=models.UniqueConstraint(
                fields=("combo", "order"), name="uq_combo_step_order"
            ),
        ),
        migrations.AddField(
            model_name="subzone",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subzones",
                to="catalog.zone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comboingredient",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="treatmentzoneconfig",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="comboingredient",
            name="subzone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.subzone",
            ),
        ),
        migrations.AddField(
            model_name="combostepitem",
            name="subzone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.subzone",
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE catalog_treatmentzoneconfig ALTER COLUMN subzone DROP NOT NULL;"
        ),
        migrations.RunSQL(
            """
        UPDATE catalog_treatmentzoneconfig
        SET subzone = NULL
        WHERE subzone IS NOT NULL;
        """
        ),
        migrations.AlterField(
            model_name="treatmentzoneconfig",
            name="subzone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.subzone",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="comboingredient",
            unique_together={("combo", "treatment", "zone", "subzone")},
        ),
        migrations.AlterUniqueTogether(
            name="treatmentzoneconfig",
            unique_together={("treatment", "zone", "subzone")},
        ),
        migrations.AddIndex(
            model_name="comboingredient",
            index=models.Index(
                fields=["combo", "treatment"], name="catalog_com_combo_i_1640c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="combostepitem",
            index=models.Index(fields=["step"], name="catalog_com_step_id_c0b4f7_idx"),
        ),
        migrations.AddIndex(
            model_name="treatmentzoneconfig",
            index=models.Index(
                fields=["treatment", "zone"], name="catalog_tre_treatme_177f6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentzoneconfig",
            index=models.Index(fields=["zone"], name="catalog_tre_zone_id_8d5c1c_idx"),
        ),
        migrations.AddConstraint(
            model_name="treatmentzoneconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration__gt", 0)), name="ck_tzc_duration_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentzoneconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="ck_tzc_price_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentzoneconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotional_price__isnull", True),
                    ("promotional_price__gt", 0),
                    _connector="OR",
                ),
                name="ck_tzc_promo_gt_0_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentzoneconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promotional_price__isnull", True),
                    ("promotional_price__lt", models.F("price")),
                    _connector="OR",
                ),
                name="ck_tzc_promo_lt_price",
            ),
        ),
        migrations.AddIndex(
            model_name="subzone",
            index=models.Index(
                fields=["zone", "name"], name="catalog_sub_zone_id_2e5c24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("zone"),
                name="uq_subzone_name_ci_per_zone",
            ),
        ),
        migrations.RemoveField(
            model_name="treatmentzoneconfig",
            name="duration_max",
        ),
    ]
