# Generated by Django 5.2.7 on 2025-11-11 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_subzone_rename_current_price_combo_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combostepitem",
            name="subzone",
        ),
        migrations.AlterUniqueTogether(
            name="comboingredient",
            unique_together={("combo", "treatment", "zone")},
        ),
        migrations.AlterUniqueTogether(
            name="treatmentzoneconfig",
            unique_together={("treatment", "zone")},
        ),
        migrations.AlterField(
            model_name="treatmentzoneconfig",
            name="body_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boca-arriba", "Boca arriba"),
                    ("boca-abajo", "Boca abajo"),
                    ("any", "Cualquiera"),
                ],
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="comboingredient",
            name="subzone",
        ),
        migrations.RemoveField(
            model_name="treatmentzoneconfig",
            name="subzone",
        ),
        migrations.CreateModel(
            name="TreatmentZoneIncompatibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "left_tzc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incompat_left",
                        to="catalog.treatmentzoneconfig",
                    ),
                ),
                (
                    "right_tzc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incompat_right",
                        to="catalog.treatmentzoneconfig",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["left_tzc"], name="catalog_tre_left_tz_cc8342_idx"
                    ),
                    models.Index(
                        fields=["right_tzc"], name="catalog_tre_right_t_f237d6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("left_tzc", "right_tzc"), name="uq_tzc_incompat_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("left_tzc", models.F("right_tzc")), _negated=True
                        ),
                        name="ck_tzc_incompat_not_self",
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="Subzone",
        ),
    ]
