# Generated by Django 5.2.7 on 2025-12-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_combo_title_alter_journey_title_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comboingredient",
            name="catalog_com_combo_i_1640c0_idx",
        ),
        migrations.AddField(
            model_name="comboingredient",
            name="treatment_zone_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="combo_ingredients",
                to="catalog.treatmentzoneconfig",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="comboingredient",
            unique_together={("combo", "treatment_zone_config")},
        ),
        migrations.AddIndex(
            model_name="comboingredient",
            index=models.Index(
                fields=["combo", "treatment_zone_config"],
                name="catalog_com_combo_i_62d49a_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="comboingredient",
            name="treatment",
        ),
        migrations.RemoveField(
            model_name="comboingredient",
            name="zone",
        ),
    ]
