# Generated by Django 5.2.7 on 2025-12-16 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0006_remove_comboingredient_catalog_com_combo_i_1640c0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="min_session_interval_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="combo",
            name="sessions",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(("sessions__gte", 1)), name="ck_combo_sessions_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_session_interval_days__gte", 0)),
                name="ck_combo_min_session_interval_days_gte_0",
            ),
        ),
    ]
