# Generated by Django 5.2.7 on 2025-12-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_combo_min_session_interval_days_combo_sessions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="combo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="combo",
            name="modal_image",
            field=models.ImageField(blank=True, null=True, upload_to="items/modals/"),
        ),
        migrations.AlterField(
            model_name="journey",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="journeys/"),
        ),
        migrations.AlterField(
            model_name="objective",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="objectives/"),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="modal_image",
            field=models.ImageField(blank=True, null=True, upload_to="items/modals/"),
        ),
    ]
