# Generated by Django 5.2.7 on 2025-12-18 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_category_image_alter_combo_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combo",
            name="image",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="modal_image",
        ),
        migrations.RemoveField(
            model_name="journey",
            name="image",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="image",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="modal_image",
        ),
        migrations.CreateModel(
            name="ComboImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/combos/", verbose_name="image"
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.combo",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JourneyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/journeys/", verbose_name="image"
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.journey",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/treatments/", verbose_name="image"
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
