# Generated by Django 5.2.7 on 2025-12-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_remove_combo_image_remove_combo_modal_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="combo",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="catalog.journey",
            ),
        ),
        migrations.AlterField(
            model_name="comboingredient",
            name="treatment_zone_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="combo_ingredients",
                to="catalog.treatmentzoneconfig",
            ),
        ),
        migrations.AlterField(
            model_name="combostepitem",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.treatment"
            ),
        ),
        migrations.AlterField(
            model_name="combostepitem",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.zone",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="journey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="catalog.journey",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentzoneconfig",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.zone"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="catalog.category",
            ),
        ),
    ]
