# Generated by Django 5.2.7 on 2025-12-29 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_combo_category_alter_combo_journey_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="combo",
            name="modal_description",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="modal_title",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="modal_description",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="modal_title",
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="combo",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="combo",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="combo",
            name="short_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="journey",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="journey",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="journey",
            name="short_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="treatment",
            name="seo_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="treatment",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="treatment",
            name="short_description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="combo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="catalog.tag"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)ss", to="catalog.tag"
            ),
        ),
    ]
