# Generated by Django 5.2.7 on 2026-01-02 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_tag_remove_combo_modal_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="default_sort",
            field=models.CharField(
                choices=[
                    ("price_asc", "Price asc"),
                    ("price_desc", "Price desc"),
                    ("az", "A-Z"),
                    ("za", "Z-A"),
                    ("newest", "Newest"),
                    ("oldest", "Oldest"),
                    ("manual", "Manual"),
                ],
                default="price_asc",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="include_journeys",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="journey_position",
            field=models.CharField(
                choices=[("FIRST", "First"), ("LAST", "Last")],
                default="LAST",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="default_sort",
            field=models.CharField(
                choices=[
                    ("price_asc", "Price asc"),
                    ("price_desc", "Price desc"),
                    ("az", "A-Z"),
                    ("za", "Z-A"),
                    ("newest", "Newest"),
                    ("oldest", "Oldest"),
                    ("manual", "Manual"),
                ],
                default="price_asc",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ItemOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context_kind",
                    models.CharField(
                        choices=[("category", "Category"), ("journey", "Journey")],
                        max_length=20,
                    ),
                ),
                ("context_id", models.UUIDField()),
                (
                    "item_kind",
                    models.CharField(
                        choices=[
                            ("treatment", "Treatment"),
                            ("combo", "Combo"),
                            ("journey", "Journey"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["context_kind", "context_id", "order"],
                        name="catalog_ite_context_eae484_idx",
                    ),
                    models.Index(
                        fields=["context_kind", "context_id"],
                        name="catalog_ite_context_b3dc69_idx",
                    ),
                ],
                "unique_together": {
                    ("context_kind", "context_id", "item_kind", "item_id")
                },
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("max_items", models.PositiveIntegerField(default=40)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="catalog_pla_slug_8cd79a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PlacementItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_kind",
                    models.CharField(
                        choices=[
                            ("treatment", "Treatment"),
                            ("combo", "Combo"),
                            ("journey", "Journey"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.UUIDField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.placement",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["placement", "order"],
                        name="catalog_pla_placeme_9fcac8_idx",
                    )
                ],
                "unique_together": {("placement", "item_kind", "item_id")},
            },
        ),
    ]
