# Generated by Django 5.2.7 on 2026-01-27 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_category_default_sort_category_include_journeys_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField(db_index=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Item benefit",
                "verbose_name_plural": "Item benefits",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemFAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField(db_index=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "Item FAQ",
                "verbose_name_plural": "Item FAQs",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemRecommendedPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.UUIDField(db_index=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Item recommended point",
                "verbose_name_plural": "Item recommended points",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="durations",
        ),
        migrations.AddField(
            model_name="combo",
            name="duration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combo",
            name="recommended_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="recommended_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("duration__isnull", True), ("duration__gt", 0), _connector="OR"
                ),
                name="ck_combo_duration_gt_0_or_null",
            ),
        ),
        migrations.AddField(
            model_name="itembenefit",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="itemfaq",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="itemrecommendedpoint",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.DeleteModel(
            name="DurationBucket",
        ),
        migrations.AddIndex(
            model_name="itembenefit",
            index=models.Index(
                fields=["content_type", "object_id", "order"],
                name="catalog_itembenefit_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemfaq",
            index=models.Index(
                fields=["content_type", "object_id", "order"],
                name="catalog_itemfaq_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemrecommendedpoint",
            index=models.Index(
                fields=["content_type", "object_id", "order"],
                name="catalog_itemrpoint_idx",
            ),
        ),
    ]
