# Generated by Django 5.2.7 on 2026-01-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_itembenefit_itemfaq_itemrecommendedpoint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="benefits_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/items/benefits/"
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="intensities",
            field=models.ManyToManyField(blank=True, to="catalog.intensitylevel"),
        ),
        migrations.AddField(
            model_name="combo",
            name="objectives",
            field=models.ManyToManyField(blank=True, to="catalog.objective"),
        ),
        migrations.AddField(
            model_name="combo",
            name="recommended_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/items/recommended/"
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="treatment_types",
            field=models.ManyToManyField(blank=True, to="catalog.treatmenttype"),
        ),
        migrations.AddField(
            model_name="objective",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="catalog.category",
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="benefits_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/items/benefits/"
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="recommended_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/items/recommended/"
            ),
        ),
    ]
