# Generated by Django 5.2.7 on 2026-02-05 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_combo_benefits_image_combo_intensities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combostepitem",
            name="step",
        ),
        migrations.RemoveField(
            model_name="combostepitem",
            name="treatment",
        ),
        migrations.RemoveField(
            model_name="combostepitem",
            name="zone",
        ),
        migrations.CreateModel(
            name="ComboSessionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_index", models.PositiveSmallIntegerField()),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_items",
                        to="catalog.combo",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.comboingredient",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ComboStep",
        ),
        migrations.DeleteModel(
            name="ComboStepItem",
        ),
        migrations.AddIndex(
            model_name="combosessionitem",
            index=models.Index(
                fields=["combo", "session_index"], name="catalog_com_combo_i_16717a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="combosessionitem",
            index=models.Index(
                fields=["ingredient"], name="catalog_com_ingredi_246be5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="combosessionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("session_index__gte", 1)),
                name="ck_combo_session_index_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="combosessionitem",
            constraint=models.UniqueConstraint(
                fields=("combo", "session_index", "ingredient"),
                name="uq_combo_session_item_unique",
            ),
        ),
    ]
