# Generated by Django 5.2.7 on 2026-02-10 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_remove_combostepitem_step_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journeyimage",
            name="journey",
        ),
        migrations.RemoveField(
            model_name="treatmentimage",
            name="treatment",
        ),
        migrations.CreateModel(
            name="ComboMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.FileField(upload_to="catalog/combos/", verbose_name="media"),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Imagen"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.combo",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JourneyMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.FileField(
                        upload_to="catalog/journeys/", verbose_name="media"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Imagen"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.journey",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.FileField(
                        upload_to="catalog/treatments/", verbose_name="media"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Imagen"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "treatment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.treatment",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="ComboImage",
        ),
        migrations.DeleteModel(
            name="JourneyImage",
        ),
        migrations.DeleteModel(
            name="TreatmentImage",
        ),
    ]
