# Generated by Django 5.2.7 on 2026-02-10 15:02

import apps.catalog.models.gallery
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_remove_journeyimage_journey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combomedia",
            name="media",
            field=apps.catalog.models.gallery.MediaField(
                max_length=255, upload_to="catalog/combos/", verbose_name="media"
            ),
        ),
        migrations.AlterField(
            model_name="journeymedia",
            name="media",
            field=apps.catalog.models.gallery.MediaField(
                max_length=255, upload_to="catalog/journeys/", verbose_name="media"
            ),
        ),
        migrations.AlterField(
            model_name="treatmentmedia",
            name="media",
            field=apps.catalog.models.gallery.MediaField(
                max_length=255, upload_to="catalog/treatments/", verbose_name="media"
            ),
        ),
    ]
