# Generated by Django 5.2.7 on 2026-02-12 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_alter_combomedia_media_alter_journeymedia_media_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="combo",
            name="ck_combo_sessions_gte_1",
        ),
        migrations.AlterField(
            model_name="combo",
            name="sessions",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_active", True), ("sessions__gte", 1)),
                    models.Q(("is_active", False), ("sessions__gte", 0)),
                    _connector="OR",
                ),
                name="ck_combo_sessions_valid",
            ),
        ),
    ]
