# Generated by Django 5.2.7 on 2026-02-17 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_remove_combo_ck_combo_sessions_gte_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="occurrences_per_period",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="session_freq",
            field=models.CharField(
                choices=[("week", "Week"), ("month", "Month")],
                default="week",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="combo",
            name="session_interval",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(("session_interval__gte", 1)),
                name="ck_combo_session_interval_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="combo",
            constraint=models.CheckConstraint(
                condition=models.Q(("occurrences_per_period__gte", 1)),
                name="ck_combo_occurrences_per_period_gte_1",
            ),
        ),
    ]
