# Generated by Django 5.2.7 on 2026-02-19 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_combo_occurrences_per_period_combo_session_freq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intensity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intensities",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="combo",
            name="treatment_types",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="treatment_types",
        ),
        migrations.RemoveField(
            model_name="combo",
            name="intensities",
        ),
        migrations.RemoveField(
            model_name="treatment",
            name="intensities",
        ),
        migrations.DeleteModel(
            name="IntensityLevel",
        ),
        migrations.DeleteModel(
            name="TreatmentType",
        ),
        migrations.AddField(
            model_name="combo",
            name="techniques",
            field=models.ManyToManyField(blank=True, to="catalog.technique"),
        ),
        migrations.AddField(
            model_name="treatment",
            name="techniques",
            field=models.ManyToManyField(blank=True, to="catalog.technique"),
        ),
        migrations.AddField(
            model_name="combo",
            name="intensities",
            field=models.ManyToManyField(blank=True, to="catalog.intensity"),
        ),
        migrations.AddField(
            model_name="treatment",
            name="intensities",
            field=models.ManyToManyField(blank=True, to="catalog.intensity"),
        ),
    ]
