# Generated by Django 5.2.7 on 2026-02-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_intensity_technique_delete_intensitylevel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="benefits_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/journeys/benefits/"
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="recommended_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="recommended_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/journeys/recommended/"
            ),
        ),
    ]
