# Generated by Django 5.2.7 on 2026-03-24 20:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_journey_benefits_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='combo',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='journey',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='journey',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['category', 'title'], name='catalog_com_categor_b6692c_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['slug'], name='catalog_com_slug_2dd214_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['category', 'title'], name='catalog_jou_categor_0e8c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['slug'], name='catalog_jou_slug_9d787c_idx'),
        ),
        migrations.AddConstraint(
            model_name='combo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('category'), name='uq_combo_slug_category_ci', violation_error_message='Ya existe Combo con este Slug en esta categoría.'),
        ),
        migrations.AddConstraint(
            model_name='combo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('category'), name='uq_combo_title_category_ci', violation_error_message='Ya existe Combo con este Title en esta categoría.'),
        ),
        migrations.AddConstraint(
            model_name='journey',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('category'), name='uq_journey_slug_category_ci', violation_error_message='Ya existe Journey con este Slug en esta categoría.'),
        ),
        migrations.AddConstraint(
            model_name='journey',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('category'), name='uq_journey_title_category_ci', violation_error_message='Ya existe Journey con este Title en esta categoría.'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), models.F('category'), name='uq_treatment_slug_category_ci', violation_error_message='Ya existe Treatment con este Slug en esta categoría.'),
        ),
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('category'), name='uq_treatment_title_category_ci', violation_error_message='Ya existe Treatment con este Title en esta categoría.'),
        ),
    ]
