# Generated by Django 5.2.7 on 2026-03-03 19:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleReviewCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("reviewer_name", models.CharField(blank=True, max_length=255)),
                ("reviewer_profile_photo_url", models.URLField(blank=True)),
                ("reviewer_is_anonymous", models.BooleanField(default=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("create_time", models.DateTimeField(blank=True, null=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(db_index=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("is_hidden", models.BooleanField(default=False)),
                ("hidden_reason", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("-update_time", "-create_time", "-fetched_at"),
                "indexes": [
                    models.Index(
                        fields=["is_hidden", "fetched_at"],
                        name="reviews_goo_is_hidd_3535fb_idx",
                    ),
                    models.Index(
                        fields=["rating", "fetched_at"],
                        name="reviews_goo_rating_124af6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManualReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author_name", models.CharField(max_length=120)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("source_label", models.CharField(default="Testimonio", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ("order", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="reviews_man_is_acti_c48e5d_idx",
                    ),
                    models.Index(
                        fields=["rating", "is_active"],
                        name="reviews_man_rating_c80e24_idx",
                    ),
                ],
            },
        ),
    ]
